"""Auto-generated by engineering-docs-agent setup. Runs at mkdocs build time
(mkdocs-gen-files) to emit one API page per module + a literate-nav SUMMARY."""
from pathlib import Path

import mkdocs_gen_files

SCAN_DIR = "scripts"
PATH_ROOT = "scripts"
OUT_ROOT = "api"

nav = mkdocs_gen_files.Nav()
root = Path(PATH_ROOT)
for py in sorted(Path(SCAN_DIR).rglob("*.py")):
    if py.name.startswith("_") or any(p in ("tests", "test") for p in py.parts):
        continue
    try:
        ident_parts = py.relative_to(root).with_suffix("").parts
    except ValueError:
        continue  # a .py outside PATH_ROOT (when SCAN_DIR is broader); skip it
    if not ident_parts:
        continue
    doc = Path(*ident_parts).with_suffix(".md")
    nav[ident_parts] = doc.as_posix()
    with mkdocs_gen_files.open(Path(OUT_ROOT, "reference") / doc, "w") as fd:
        ident = ".".join(ident_parts)
        fd.write(f"# `{ident}`\n\n::: {ident}\n")
    mkdocs_gen_files.set_edit_path(Path(OUT_ROOT, "reference") / doc, py)

with mkdocs_gen_files.open(Path(OUT_ROOT, "reference", "SUMMARY.md"), "w") as f:
    f.writelines(nav.build_literate_nav())
