"""Auto-generated by engineering-docs-agent setup. Runs at mkdocs build time
(mkdocs-gen-files) to emit one API page per module + a literate-nav SUMMARY,
grouped by service/component when GROUPS is non-empty (CCE-105)."""
import fnmatch
from pathlib import Path

import mkdocs_gen_files

SCAN_DIR = "scripts"
PATH_ROOT = "scripts"
OUT_ROOT = "api"
GROUPS = [{'name': 'Orchestrator', 'modules': ['orchestrator_runner', 'state_io', 'contracts', 'stderr_emit']}, {'name': 'Generators', 'modules': ['archive_indexes', 'contracts_doc', 'core_manifest', 'site_structure', 'source_map', 'source_drift', 'frontmatter_contract']}, {'name': 'Lint', 'modules': ['lint/*']}, {'name': 'Setup', 'modules': ['setup_discover', 'setup_scaffold', 'preflight_host', 'scaffold_workflow', 'enable_pages']}, {'name': 'Verification', 'modules': ['verify_citations', 'verify_diagrams', 'verify_runner']}, {'name': 'Integrations', 'modules': ['gh_client', 'jira_transition_on_merge', 'prune_merged_branches']}]


def assign_group(ident: str, groups: list) -> str:
    """Return the name of the first group whose module glob matches ``ident``,
    else "Other". An empty ``groups`` returns "" so the caller keeps the flat
    nav. Globs match against both the dotted ident ("a.b") and its path form
    ("a/b"), so a "lint/*" pattern matches a "lint.lint_runner" module.

    This function is embedded verbatim into the generated gen_ref_pages.py
    (see _GEN_REF_TEMPLATE) via inspect.getsource -- keep it self-contained:
    use only the stdlib ``fnmatch`` imported at the template's top, and no
    brace literals (so str.format on the template is safe).
    """
    if not groups:
        return ""
    path_form = ident.replace(".", "/")
    for group in groups:
        for pattern in group.get("modules", []):
            if fnmatch.fnmatchcase(ident, pattern) or fnmatch.fnmatchcase(
                path_form, pattern
            ):
                return group["name"]
    return "Other"


nav = mkdocs_gen_files.Nav()
root = Path(PATH_ROOT)
for py in sorted(Path(SCAN_DIR).rglob("*.py")):
    if py.name.startswith("_") or any(p in ("tests", "test") for p in py.parts):
        continue
    try:
        ident_parts = py.relative_to(root).with_suffix("").parts
    except ValueError:
        continue  # a .py outside PATH_ROOT (when SCAN_DIR is broader); skip it
    if not ident_parts:
        continue
    doc = Path(*ident_parts).with_suffix(".md")
    ident = ".".join(ident_parts)
    group = assign_group(ident, GROUPS)
    nav_key = (group, *ident_parts) if group else ident_parts
    nav[nav_key] = doc.as_posix()
    with mkdocs_gen_files.open(Path(OUT_ROOT, "reference") / doc, "w") as fd:
        fd.write(f"# `{ident}`\n\n::: {ident}\n")
    mkdocs_gen_files.set_edit_path(Path(OUT_ROOT, "reference") / doc, py)

with mkdocs_gen_files.open(Path(OUT_ROOT, "reference", "SUMMARY.md"), "w") as f:
    f.writelines(nav.build_literate_nav())
