"""Orchestrator runner. Used by GitHub Actions and integration tests.

Calls subagents via the Claude Code CLI in production. In `--dry-run-subagents`
mode (used in tests), reads canned JSON outputs from a fixture directory
instead of invoking Claude.
"""

from __future__ import annotations
import argparse, json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import yaml


def load_yaml(p: Path) -> dict[str, Any]:
    return yaml.safe_load(p.read_text()) or {}


def load_json(p: Path) -> dict[str, Any]:
    return json.loads(p.read_text()) if p.exists() else {}


def dispatch_subagent(name: str, inputs: dict, *, dry_run_dir: Path | None) -> dict:
    """Dispatch a subagent. Returns parsed JSON output.

    In dry-run mode, reads from `<dry_run_dir>/fake_<name_with_underscores>.json`
    instead of invoking Claude.
    """
    if dry_run_dir is not None:
        fixture = dry_run_dir / f"fake_{name.replace('-', '_')}.json"
        if not fixture.exists():
            return {}
        return load_json(fixture)
    payload = json.dumps(inputs)
    r = subprocess.run(
        ["claude", "agent", name, "--input", payload],
        capture_output=True,
        text=True,
        check=False,
    )
    if r.returncode != 0:
        raise RuntimeError(f"subagent {name} failed: {r.stderr[:500]}")
    return json.loads(r.stdout)


def run(repo_root: Path, *, dry_run_dir: Path | None, no_pr: bool) -> int:
    cfg_path = repo_root / ".engineering-docs-agent" / "config.yml"
    state_path = repo_root / ".engineering-docs-agent" / "state.json"
    if not cfg_path.exists():
        print("no config", file=sys.stderr)
        return 2

    config = load_yaml(cfg_path)
    state = load_json(state_path)
    state.setdefault("version", "1")

    head_sha = (
        subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
        ).stdout.strip()
        or "unknown"
    )

    now = datetime.now(timezone.utc).isoformat()
    state["current_run"] = {
        "started_at": now,
        "head_sha": head_sha,
        "partial": False,
        "partial_reasons": [],
    }

    sources = dispatch_subagent(
        "source-collector",
        {
            "last_sha": state.get("last_successful_run", {}).get("head_sha", ""),
            "head_sha": head_sha,
            "repo": {"owner": "x", "name": "y"},
            "pr_branch_filter": ["docs-agent/*"],
        },
        dry_run_dir=dry_run_dir,
    )

    prs = sources.get("prs", [])
    summaries = []
    for pr in prs:
        summary = dispatch_subagent(
            "pr-summarizer",
            {
                "pr": pr,
                "jira_context": [],
                "lens_names": list(config.get("docs", {}).get("lens_paths", {}).keys()),
            },
            dry_run_dir=dry_run_dir,
        )
        summaries.append(summary)

    # Page authoring: aggregate doc_targets per lens.
    per_lens: dict[str, list[dict]] = {}
    for s in summaries:
        for t in s.get("doc_targets", []):
            per_lens.setdefault(t["lens"], []).append({"target": t, "summary": s})

    authored: list[str] = []
    for lens, batch in per_lens.items():
        for item in batch:
            t = item["target"]
            target_path = (
                repo_root / config["docs"]["lens_paths"][lens] / t["page_hint"]
            )
            target_path.parent.mkdir(parents=True, exist_ok=True)
            out = dispatch_subagent(
                "page-author",
                {
                    "target_path": str(target_path),
                    "action": t["action"],
                    "lens": lens,
                    "summaries": [item["summary"]],
                    "voice_samples": [],
                    "frontmatter_template": {
                        "status": "draft",
                        "sources": [],
                        "synthesized_into": [],
                    },
                },
                dry_run_dir=dry_run_dir,
            )
            if out.get("ok"):
                authored.append(str(target_path))
                if dry_run_dir and not target_path.exists():
                    target_path.write_text(
                        "---\nstatus: draft\nsources: []\nsynthesized_into: []\n---\n"
                        f"# {t['page_hint']}\n\nGenerated by docs-agent.\n"
                    )

    # Content validation
    if authored:
        validation = dispatch_subagent(
            "content-validator",
            {
                "paths": authored,
                "config_path": str(cfg_path),
                "voice_samples": [],
            },
            dry_run_dir=dry_run_dir,
        )
        for fail in validation.get("failed", []):
            if fail.get("severity") == "block":
                Path(fail["path"]).unlink(missing_ok=True)
                state["current_run"]["partial"] = True
                state["current_run"]["partial_reasons"].append(
                    f"lint_block: {fail['path']} {fail['rule']}: {fail['message']}"
                )

    # Gap detection
    dismissed = set(state.get("dismissed_gap_flags", {}).keys())
    gap_verdicts = []
    for pr in prs:
        pr_id = f"x/y#{pr['number']}"
        if pr_id in dismissed:
            continue
        verdict = dispatch_subagent(
            "gap-detector",
            {
                "pr": pr,
                "config": {
                    "allowlist_paths": config.get("gap_detection", {}).get(
                        "allowlist_paths", []
                    ),
                    "size_filter": config.get("gap_detection", {}).get(
                        "size_filter", {}
                    ),
                },
                "dismissed_flags": list(dismissed),
            },
            dry_run_dir=dry_run_dir,
        )
        gap_verdicts.append(verdict)

    # Prepend What's New entry
    whats_new = repo_root / config["docs"]["whats_new_file"]
    whats_new.parent.mkdir(parents=True, exist_ok=True)
    entry_lines = [f"## {now}"]
    for s in summaries:
        entry_lines.append(f"- PR #{s.get('pr_number')}: {s.get('what_changed', '')}")
    gaps_flagged = [v for v in gap_verdicts if v.get("needs_spec")]
    if gaps_flagged:
        entry_lines.append("### Gaps flagged")
        for g in gaps_flagged:
            entry_lines.append(f"- {g['pr_id']}: {g['reasoning']}")
    entry = "\n".join(entry_lines) + "\n\n"
    existing = whats_new.read_text() if whats_new.exists() else ""
    whats_new.write_text(entry + existing)

    state_path.write_text(json.dumps(state, indent=2))

    if no_pr:
        return 0
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--dry-run-subagents", type=Path, default=None)
    parser.add_argument("--no-pr", action="store_true")
    args = parser.parse_args()
    return run(args.repo_root, dry_run_dir=args.dry_run_subagents, no_pr=args.no_pr)


if __name__ == "__main__":
    sys.exit(main())
